### ISSUE TITLE
Port forwarding not working

### ISSUE THREAD

**Issue by Theangelofspace15** [aus/pfatt#18]
I setup the pfsense box with the script. Internet is working fine, but i tried to forward some ports but when  i go online and check if the port are open, they show as close. I am using CanYouSeeMe.org
 to check my ports

**Comment by BigDogJonx** [comment]
Im not having any issues on this, is your pfsense WAN interface showing the public IP on the dashboard?  Or when you go to Status, Interfaces?

**Comment by Theangelofspace15** [comment]
Yes. It is, but the port i open show as close.

**Comment by BigDogJonx** [comment]
Whats the details of your setup?  What ATT Fiber RG model do you have? 
Ive personally done this on my PACE 5268AC and my other house which has the Arris NVG589 and both have open ports we have setup for other use.

Are you sure your WAN is tied to ngeth0 interface?  Also for that interface, are the Firewall Rules enabled for those ports that are opened?

**Comment by Theangelofspace15** [comment]
BGW210. Yes im sure, I am getting 600/200 ish out of my 1gbs plan. The internet works, but ai can not port forward. I srt a port forward rule, but it still shows close.

**Comment by Theangelofspace15** [comment]
I set the port forward for pass. The interface on have the default rules.

**Comment by BigDogJonx** [comment]
Not fully understanding you.  When creating port forwards in pfsense, you normally go to Firewall, NAT.  That is where your port forwards are setup.  Once you create a port forward (lets say you opened port 80 to go to your server which is 192.168.0.2), it will automatically create the respective rule on your WAN interface (as long as you kept the interface to WAN on the portforward NAT rule, which is the default).  So normally I dont mess with Firewall, Rules, WAN interface in the sense where I dont edit those rules there to open ports.  Those rules are created by the Firewall, NAT side.

**Comment by Theangelofspace15** [comment]
You actually have the option to PASS the rule, and skip firewall. I tried both. Right now I have a rule for the fw on the wan interface as well as a floating rule just to b sure.

**Comment by BigDogJonx** [comment]
Sorry then I cant come up with anything else.  In my opinion I dont think it has to do with this bypass script mainly because its just a virtual interface and once that interface has the public IP, its now all upto pfsense to handle everything from there as far as port forwards, firewall rules, etc.  The script really doesnt do anything there to prevent port forwards as its just bridging two ports and allowing only the 802.1/x traffic to pass to allow RG to be authenticated.  Now granted Im not the author of this so thats just my opinion based on what I can see in the script as well as that I have this running fine at two houses and have port forwards setup (which were done via Firewall, NAT, Port Forward) for our servers and dont have any issues. All I can suggest is making sure you have the script and files that needed to be copied to pfsense validated, make sure permissions are right.  But sounds like most of that probably is right since you are saying you are getting a public IP on your WAN (ngeth0 interface) which sort of tells me this is working.

**Comment by aus** [comment]
Closing this as user error.
