### ISSUE TITLE
Document U-Verse TV Setup

### ISSUE THREAD

**Issue by aus** [aus/pfatt#3]
I don't have a TV subscription anymore to test this. However, in my previous setup, it involved something like:

- Adding firewall rules to allow IGMP traffic
- Determining the AT&T IPTV ranges
- Enabling those ranges in the IGMP Proxy settings in pfSense

**Comment by Theangelofspace15** [comment]
I just got att installed and i do have uverse. I started to setup everything with your script and internet is now working on a pfsense vm if you need someone to test/setup uverse let me know, cause that will be my next step.

**Comment by aus** [comment]
It looks like there were some notes for TV setup posted on Reddit. I will keep the issue open in case anyone wants to add the notes to the README.

https://www.reddit.com/r/PFSENSE/comments/ag43rb/att_bgw210_true_independent_bridge_mode_uverse/

**Comment by Kokoro-Concord** [comment]
> It looks like there were some notes for TV setup posted on Reddit. I will keep the issue open in case anyone wants to add the notes to the README.
> 
> https://www.reddit.com/r/PFSENSE/comments/ag43rb/att_bgw210_true_independent_bridge_mode_uverse/

I just followed the instructions in this guide, and although I had to deviate a little bit and do some extra troubleshooting I was able to get U-verse TV working perfectly. I'm looking to submit a PR to update the readme with documentation sometime soon and get some input on any changes as you see fit.

**Comment by maguilu** [comment]
I just followed the instructions in this guide, and although I had to deviate a little bit and do some extra troubleshooting I was able to get U-verse TV working perfectly. I'm looking to submit a PR to update the readme with documentation sometime soon and get some input on any changes as you see fit.


Can you detail the deviations for the documented process. I seam to be close but no cigar. TV comes in for a few secs and then goes blank. I believe is related to IGMP of firewall rules but don’t have much time to troubleshoot as the kids get restless and need to return things to normal. If you can documents the differences maybe it can get me to make them and me happy

**Comment by Kokoro-Concord** [comment]
> I just followed the instructions in this guide, and although I had to deviate a little bit and do some extra troubleshooting I was able to get U-verse TV working perfectly. I'm looking to submit a PR to update the readme with documentation sometime soon and get some input on any changes as you see fit.
> 
> Can you detail the deviations for the documented process. I seam to be close but no cigar. TV comes in for a few secs and then goes blank. I believe is related to IGMP of firewall rules but don’t have much time to troubleshoot as the kids get restless and need to return things to normal. If you can documents the differences maybe it can get me to make them and me happy

I apologize I had sat on this guide for a while; I had become busy with work around the time I first gotten it working.
If when you say the TV comes in for a few seconds and then goes blank, this is because the U-verse TV box is not receiving multicast traffic. In my setup I have the U-verse TV box in its own LAN (this requires an additional interface on your pfSense machine), and I created two floating rules that allow all multicast traffic to that network. The rules should be setup as follows:

_Action:_ Pass
_Quick:_ Checked
_Interface:_ WAN and DVR Network
_Address Family:_ IPv4
_Destination Address:_ 224.0.0.0/8, 239.0.0.0/8
_Allow IP Options:_ Checked

I hadn't forgotten about my promise to submit an actual PR for the U-verse TV setup, but lately I've been rethinking how it's formatted. I may just push it as soon as it's ready and make changes later as needed.

**Comment by maguilu** [comment]
Let try that, i have those rules in the wan side I will recreate as floating.

Keep you posted.

Thanks

Miguel
maguilu@me.com

**Comment by 0xC0ncord** [comment]
Sorry for the long wait. I've created #31 at last. Please give it a try and let me know if it worked for you.

**Comment by aus** [comment]
Closing this since we have some doc thanks to @0xC0ncord. If there's issues with the doc, we can open a new issue.
